// react/src/components/Header.js
import React, {Fragment, Component} from 'react'
import {Link} from 'react-router-dom'

import Modal from './Modal'
import Balance from './Balance'

import history from '../history'

import './Header.css'

class Header extends Component {
  state = {
    isShow: false,
    searchAddress: '',
    startAddress: ''
  }

  componentDidMount() {
    // console.log(this.props);
    // this.props.contract.getBalanceByEscrowId.call(0, {
    //   from: fromAccount,
    //   gas: gasLimit,
    //   gasPrice: gasPriceInWei
    // });
  }

  handleModal = (show) => () => {
    const {startAddress} = this.state;
    this.setState({
      isShow: show,
      ...show
        ? {}
        : {
          startAddress: ''
        }
    })
  }

  handleChangeInput = (name) => (e) => {
    this.setState({[name]: e.target.value})
  }

  createEscrow = () => {
    console.log(this.props);
  }

  handleLogout = () => {
    this.props.removeWalletAddress()
    history.push('/')
  }

  render() {
    const {isShow, startAddress, searchAddress} = this.state;

    return (
			<Fragment>
	      <div className="header" key="header">
	        <div className='container'>
	          <div className="header--top">
	            <Link to="/" className="header--logo">DESCRO</Link>
	            <div className="header--search">
	              <input type="text" className='header--search-input' placeholder="Search for a deal" value={searchAddress} onChange={this.handleChangeInput('searchAddress')}/>
	            </div>
	            <div className="header--address">My Account</div>
	          </div>
	          <div className="header--bottom">
	            <div className="balance-wrap">
	              <span className="balance-name">BALANCE</span>
	              {
	                this.props.address && (<div className="header--address">
	                  <button>My Account</button>
	                  <button onClick={this.handleLogout}>Logout</button>
	                </div>)
	              }
	            </div>
	            <div className="header--bottom">
	              <Balance balance={12}/>
	              <div className="header--action">
	                <div className="header--intro">
	                  <div className="intro-title">DESCRO</div>
	                  <div className="intro-body">Decentralized Escrow for Ethereum</div>
	                </div>
	                <button className="btn" onClick={this.handleModal(true)}>Start Deal</button>
	              </div>
	            </div>
	          </div>
	        </div>
	      </div>
	      <Modal key='modal' isShow={isShow} hideModal={this.handleModal(false)}>
	        Start Deal Modal
	        <div>
	          <label htmlFor="buyerAddress">Seller Address</label>
	          <input type='text' id="buyerAddress" value={startAddress} onChange={this.handleChangeInput('startAddress')}/>
	        </div>
	        <div>
	          <button className="btn" onClick={this.handleModal(false)}>Cancel</button>
	          <button className="btn" onClick={this.createEscrow}>Confirm</button>
	        </div>
	      </Modal>
	    </Fragment>
		)
  }
}

export default Header

// vue/src/components/Header.vue
<template>
  <div class="header">
		<div class="container">
			<div class="header--top">
				<div class="header--logo">DESCRO</div>
				<div class="header--search">
					<input class="header--search-input" type="text" placeholder="Search for a deal" />
				</div>
				<div class="header--address">My Account</div>
			</div>
			<div class="header--bottom">
				<div class="balance-wrap">
					<span class="balance-name">BALANCE</span>
					<div class="balance-value">
						<span class="balance-value--val">153</span>
						<span class="balance-value--unit">ETH</span>
					</div>
				</div>
				<div class="header--action">
					<div class="header--intro">
						<div class="intro-title">DESCRO</div>
						<div class="intro-body">Decentralized Escrow for Ethereum</div>
					</div>
					<button class="btn">Start Deal</button>
				</div>
			</div>
		</div>
  </div>
</template>

<script>
export default {
  name: "Header",
  props: {}
};
</script>

<style scoped lang="scss">
.header {
  display: flex;
	flex-direction: column;
	align-items: center;
	width: 100%;
	min-height: 80px;
	background: #000;
	color: #fff;
}

.header--address {
	margin-left: auto;
}

.header--top {
	display: flex;
	flex-direction: row;
	width: 100%;
	min-height: 80px;
	align-items: center;
	padding: 0 30px;
}

.header--search {
	margin-left: 20px;
	.header--search-input {
		margin-bottom: 0;
		color: #fff;
	}
}

.header--intro {
	text-align: left;
	.intro-title {
		font-size: 2em;
	}
	.intro-body {
		margin-bottom: 20px;
	}	
}

.header--bottom {
	display: flex;
	flex-direction: row;
	justify-content: space-around;
	align-items: center;
	width: 100%;
	padding: 10px 0 40px;
	text-align: left;
}

.header--logo {
}

.balance-wrap {
	text-align: left;
	.balance-name {
		opacity: .7;
	}
	.balance-value {
		.balance-value--val {
			font-size: 2.5em;
		}
		.balance-value--unit {
			font-size: 1.5em;
			opacity: .8;
			margin-left: 10px;
		}
	}
}

</style>
